---
    - name: Redémarrer apache2
      become: yes
      service:
        name: httpd
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

...